//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zarkiaclb
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAuthentication
    {
        public decimal autID { get; set; }
        public string UserID { get; set; }
        public string UserName { get; set; }
        public string UserLName { get; set; }
        public string UserPhoneNumber { get; set; }
        public bool UserActive { get; set; }
        public string DeactiveReason { get; set; }
    }
}
