//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace zarkiaclb
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSalInsurenceDiskFactory
    {
        public int insAutoID { get; set; }
        public string DSK_ID { get; set; }
        public string DSK_NAME { get; set; }
        public string DSK_FARM { get; set; }
        public string DSK_ADRS { get; set; }
    }
}
