using DevExpress.Utils;
using DevExpress.XtraPrinting;
using DevExpress.XtraReports.UI;
using FishHoghoghi.FishDataSetTableAdapters;
using System;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Drawing.Printing;
using System.Windows.Forms;

namespace Fish.Reports
{
    public class XtraReport1 : XtraReport
    {
        private string startDate;
        private string endDate;
        private IContainer components = null;
        private TopMarginBand TopMargin;
        private BottomMarginBand BottomMargin;
        private DetailBand Detail;
        private XRPanel xrPanel1;
        private XRLabel xrLabel14;
        private XRLabel xrLabel15;
        private XRLabel xrLabel12;
        private XRLabel xrLabel13;
        private XRLabel xrLabel10;
        private XRLabel xrLabel11;
        private XRLabel xrLabel9;
        private XRLabel xrLabel8;
        private XRLabel xrLabel7;
        private XRLabel xrLabel6;
        private XRLabel xrLabel5;
        private XRLabel xrLabel4;
        private XRLabel xrLabel3;
        private XRLabel xrLabel2;
        private XRLabel xrLabel1;
        private XRLabel xrLabel22;
        private XRLabel xrLabel23;
        private XRLabel xrLabel26;
        private XRLabel xrLabel27;
        private XRLabel xrLabel16;
        private XRLabel xrLabel17;
        private XRLabel xrLabel18;
        private XRLabel xrLabel19;
        private XRLabel xrLabel20;
        private XRLabel xrLabel21;
        private XRLabel xrLabel31;
        private XRLabel xrLabel32;
        private XRLabel xrLabel33;
        private XRLabel xrLabel34;
        private XRLabel xrLabel25;
        private XRLabel xrLabel28;
        private XRLabel xrLabel29;
        private XRLabel xrLabel30;
        private XRLabel xrLabel24;
        private XRLabel xrLabel47;
        private XRLabel xrLabel48;
        private XRLabel xrLabel45;
        private XRLabel xrLabel46;
        private XRLabel xrLabel43;
        private XRLabel xrLabel44;
        private XRLabel xrLabel42;
        private XRLabel xrLabel40;
        private XRLabel xrLabel41;
        private XRLabel xrLabel38;
        private XRLabel xrLabel39;
        private XRLabel xrLabel36;
        private XRLabel xrLabel37;
        private XRLabel xrLabel35;
        private XRLabel xrLabel63;
        private XRLabel xrLabel62;
        private XRLabel xrLabel61;
        private XRLabel xrLabel59;
        private XRLabel xrLabel60;
        private XRLabel xrLabel57;
        private XRLabel xrLabel58;
        private XRLabel xrLabel55;
        private XRLabel xrLabel53;
        private XRLabel xrLabel54;
        private XRLabel xrLabel52;
        private XRLabel xrLabel51;
        private XRLabel xrLabel49;
        private XRLabel xrLabel93;
        private XRLabel xrLabel94;
        private XRLabel xrLabel95;
        private XRLabel xrLabel96;
        private XRLabel xrLabel84;
        private XRLabel xrLabel85;
        private XRLabel xrLabel86;
        private XRLabel xrLabel87;
        private XRLabel xrLabel88;
        private XRLabel xrLabel89;
        private XRLabel xrLabel90;
        private XRLabel xrLabel91;
        private XRLabel xrLabel92;
        private XRLabel xrLabel83;
        private XRLabel xrLabel82;
        private XRLabel xrLabel81;
        private XRLabel xrLabel80;
        private XRLabel xrLabel79;
        private XRLabel xrLabel78;
        private XRLabel xrLabel77;
        private XRLabel xrLabel76;
        private XRLabel xrLabel75;
        private XRLabel xrLabel74;
        private XRLabel xrLabel73;
        private XRLabel xrLabel70;
        private XRLabel xrLabel71;
        private XRLabel xrLabel72;
        private XRLabel xrLabel69;
        private XRLabel xrLabel68;
        private XRLabel xrLabel67;
        private XRLabel xrLabel66;
        private XRLabel xrLabel65;
        private XRLabel xrLabel64;
        private XRLabel xrLabel50;
        private BindingSource bindingSource1;
        private FishDataSet fishDataSet;
        private MKView_ContractHamkaranTableAdapter mKView_ContractHamkaranTableAdapter;
        private XRLabel xrLabel56;

        public XtraReport1(string username, string year, string month)
        {
            this.InitializeComponent();
            this.mKView_ContractHamkaranTableAdapter.Fill(this.fishDataSet.MKView_ContractHamkaran, username);
            this.startDate = year + "/" + month + "/01";
            int num = new MD.PersianDateTime.PersianDateTime(Convert.ToInt32(year), Convert.ToInt32(month), 1).GetMonthDays;
            string[] textArray1 = new string[] { year, "/", month, "/", num.ToString() };
            this.endDate = string.Concat(textArray1);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing && (this.components != null))
            {
                this.components.Dispose();
            }
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            this.components = new Container();
            this.TopMargin = new TopMarginBand();
            this.BottomMargin = new BottomMarginBand();
            this.Detail = new DetailBand();
            this.xrPanel1 = new XRPanel();
            this.xrLabel56 = new XRLabel();
            this.xrLabel50 = new XRLabel();
            this.xrLabel93 = new XRLabel();
            this.xrLabel94 = new XRLabel();
            this.xrLabel95 = new XRLabel();
            this.xrLabel96 = new XRLabel();
            this.xrLabel84 = new XRLabel();
            this.xrLabel85 = new XRLabel();
            this.xrLabel86 = new XRLabel();
            this.xrLabel87 = new XRLabel();
            this.xrLabel88 = new XRLabel();
            this.xrLabel89 = new XRLabel();
            this.xrLabel90 = new XRLabel();
            this.xrLabel91 = new XRLabel();
            this.xrLabel92 = new XRLabel();
            this.xrLabel83 = new XRLabel();
            this.xrLabel82 = new XRLabel();
            this.xrLabel81 = new XRLabel();
            this.xrLabel80 = new XRLabel();
            this.xrLabel79 = new XRLabel();
            this.xrLabel78 = new XRLabel();
            this.xrLabel77 = new XRLabel();
            this.xrLabel76 = new XRLabel();
            this.xrLabel75 = new XRLabel();
            this.xrLabel74 = new XRLabel();
            this.xrLabel73 = new XRLabel();
            this.xrLabel70 = new XRLabel();
            this.xrLabel71 = new XRLabel();
            this.xrLabel72 = new XRLabel();
            this.xrLabel69 = new XRLabel();
            this.xrLabel68 = new XRLabel();
            this.xrLabel67 = new XRLabel();
            this.xrLabel66 = new XRLabel();
            this.xrLabel65 = new XRLabel();
            this.xrLabel64 = new XRLabel();
            this.xrLabel63 = new XRLabel();
            this.xrLabel62 = new XRLabel();
            this.xrLabel61 = new XRLabel();
            this.xrLabel59 = new XRLabel();
            this.xrLabel60 = new XRLabel();
            this.xrLabel57 = new XRLabel();
            this.xrLabel58 = new XRLabel();
            this.xrLabel55 = new XRLabel();
            this.xrLabel53 = new XRLabel();
            this.xrLabel54 = new XRLabel();
            this.xrLabel52 = new XRLabel();
            this.xrLabel51 = new XRLabel();
            this.xrLabel49 = new XRLabel();
            this.xrLabel47 = new XRLabel();
            this.xrLabel48 = new XRLabel();
            this.xrLabel45 = new XRLabel();
            this.xrLabel46 = new XRLabel();
            this.xrLabel43 = new XRLabel();
            this.xrLabel44 = new XRLabel();
            this.xrLabel42 = new XRLabel();
            this.xrLabel40 = new XRLabel();
            this.xrLabel41 = new XRLabel();
            this.xrLabel38 = new XRLabel();
            this.xrLabel39 = new XRLabel();
            this.xrLabel36 = new XRLabel();
            this.xrLabel37 = new XRLabel();
            this.xrLabel35 = new XRLabel();
            this.xrLabel31 = new XRLabel();
            this.xrLabel32 = new XRLabel();
            this.xrLabel33 = new XRLabel();
            this.xrLabel34 = new XRLabel();
            this.xrLabel25 = new XRLabel();
            this.xrLabel28 = new XRLabel();
            this.xrLabel29 = new XRLabel();
            this.xrLabel30 = new XRLabel();
            this.xrLabel24 = new XRLabel();
            this.xrLabel22 = new XRLabel();
            this.xrLabel23 = new XRLabel();
            this.xrLabel26 = new XRLabel();
            this.xrLabel27 = new XRLabel();
            this.xrLabel16 = new XRLabel();
            this.xrLabel17 = new XRLabel();
            this.xrLabel18 = new XRLabel();
            this.xrLabel19 = new XRLabel();
            this.xrLabel20 = new XRLabel();
            this.xrLabel21 = new XRLabel();
            this.xrLabel14 = new XRLabel();
            this.xrLabel15 = new XRLabel();
            this.xrLabel12 = new XRLabel();
            this.xrLabel13 = new XRLabel();
            this.xrLabel10 = new XRLabel();
            this.xrLabel11 = new XRLabel();
            this.xrLabel9 = new XRLabel();
            this.xrLabel8 = new XRLabel();
            this.xrLabel7 = new XRLabel();
            this.xrLabel6 = new XRLabel();
            this.xrLabel5 = new XRLabel();
            this.xrLabel4 = new XRLabel();
            this.xrLabel3 = new XRLabel();
            this.xrLabel2 = new XRLabel();
            this.xrLabel1 = new XRLabel();
            this.bindingSource1 = new BindingSource(this.components);
            this.fishDataSet = new FishDataSet();
            this.mKView_ContractHamkaranTableAdapter = new MKView_ContractHamkaranTableAdapter();
            ((ISupportInitialize)this.bindingSource1).BeginInit();
            this.fishDataSet.BeginInit();
            this.BeginInit();
            this.TopMargin.HeightF = 0f;
            this.TopMargin.Name = "TopMargin";
            this.BottomMargin.HeightF = 79f;
            this.BottomMargin.Name = "BottomMargin";
            XRControl[] controls = new XRControl[] { this.xrPanel1, this.xrLabel2, this.xrLabel1 };
            this.Detail.Controls.AddRange(controls);
            this.Detail.HeightF = 762.5f;
            this.Detail.Name = "Detail";
            this.Detail.StylePriority.UseTextAlignment = false;
            this.Detail.TextAlignment = TextAlignment.MiddleLeft;
            this.xrPanel1.Borders = BorderSide.All;
            XRControl[] controlArray2 = new XRControl[] {
                this.xrLabel56, this.xrLabel50, this.xrLabel93, this.xrLabel94, this.xrLabel95, this.xrLabel96, this.xrLabel84, this.xrLabel85, this.xrLabel86, this.xrLabel87, this.xrLabel88, this.xrLabel89, this.xrLabel90, this.xrLabel91, this.xrLabel92, this.xrLabel83,
                this.xrLabel82, this.xrLabel81, this.xrLabel80, this.xrLabel79, this.xrLabel78, this.xrLabel77, this.xrLabel76, this.xrLabel75, this.xrLabel74, this.xrLabel73, this.xrLabel70, this.xrLabel71, this.xrLabel72, this.xrLabel69, this.xrLabel68, this.xrLabel67,
                this.xrLabel66, this.xrLabel65, this.xrLabel64, this.xrLabel63, this.xrLabel62, this.xrLabel61, this.xrLabel59, this.xrLabel60, this.xrLabel57, this.xrLabel58, this.xrLabel55, this.xrLabel53, this.xrLabel54, this.xrLabel52, this.xrLabel51, this.xrLabel49,
                this.xrLabel47, this.xrLabel48, this.xrLabel45, this.xrLabel46, this.xrLabel43, this.xrLabel44, this.xrLabel42, this.xrLabel40, this.xrLabel41, this.xrLabel38, this.xrLabel39, this.xrLabel36, this.xrLabel37, this.xrLabel35, this.xrLabel31, this.xrLabel32,
                this.xrLabel33, this.xrLabel34, this.xrLabel25, this.xrLabel28, this.xrLabel29, this.xrLabel30, this.xrLabel24, this.xrLabel22, this.xrLabel23, this.xrLabel26, this.xrLabel27, this.xrLabel16, this.xrLabel17, this.xrLabel18, this.xrLabel19, this.xrLabel20,
                this.xrLabel21, this.xrLabel14, this.xrLabel15, this.xrLabel12, this.xrLabel13, this.xrLabel10, this.xrLabel11, this.xrLabel9, this.xrLabel8, this.xrLabel7, this.xrLabel6, this.xrLabel5, this.xrLabel4, this.xrLabel3
            };
            this.xrPanel1.Controls.AddRange(controlArray2);
            this.xrPanel1.LocationFloat = new PointFloat(3.166707f, 54f);
            this.xrPanel1.Name = "xrPanel1";
            this.xrPanel1.RightToLeft = DevExpress.XtraReports.UI.RightToLeft.Yes;
            this.xrPanel1.SizeF = new SizeF(742.8334f, 698.5f);
            this.xrPanel1.StylePriority.UseBorders = false;
            this.xrLabel56.Borders = BorderSide.Top | BorderSide.Left;
            this.xrLabel56.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel56.LocationFloat = new PointFloat(204.0834f, 565.6669f);
            this.xrLabel56.Multiline = true;
            this.xrLabel56.Name = "xrLabel56";
            this.xrLabel56.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel56.SizeF = new SizeF(74.33325f, 27f);
            this.xrLabel56.StylePriority.UseBorders = false;
            this.xrLabel56.StylePriority.UseFont = false;
            this.xrLabel56.StylePriority.UseTextAlignment = false;
            this.xrLabel56.Text = "بن :";
            this.xrLabel56.TextAlignment = TextAlignment.MiddleCenter;
            this.xrLabel50.Borders = BorderSide.Top;
            ExpressionBinding[] items = new ExpressionBinding[] { new ExpressionBinding("BeforePrint", "Text", "[مدت قرارداد]") };
            this.xrLabel50.ExpressionBindings.AddRange(items);
            this.xrLabel50.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel50.LocationFloat = new PointFloat(0.8332222f, 242f);
            this.xrLabel50.Multiline = true;
            this.xrLabel50.Name = "xrLabel50";
            this.xrLabel50.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel50.SizeF = new SizeF(79.00002f, 27.33322f);
            this.xrLabel50.StylePriority.UseBorders = false;
            this.xrLabel50.StylePriority.UseFont = false;
            this.xrLabel93.Borders = BorderSide.Top | BorderSide.Left;
            ExpressionBinding[] bindingArray2 = new ExpressionBinding[] { new ExpressionBinding("BeforePrint", "Text", "[حقوق پایه]") };
            this.xrLabel93.ExpressionBindings.AddRange(bindingArray2);
            this.xrLabel93.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel93.LocationFloat = new PointFloat(0f, 349.6664f);
            this.xrLabel93.Multiline = true;
            this.xrLabel93.Name = "xrLabel93";
            this.xrLabel93.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel93.SizeF = new SizeF(139.8749f, 27f);
            this.xrLabel93.StylePriority.UseBorders = false;
            this.xrLabel93.StylePriority.UseFont = false;
            this.xrLabel93.StylePriority.UseTextAlignment = false;
            this.xrLabel93.TextAlignment = TextAlignment.MiddleCenter;
            this.xrLabel93.TextFormatString = "{0:###,# ریال}";
            this.xrLabel94.Borders = BorderSide.Top | BorderSide.Left;
            ExpressionBinding[] bindingArray3 = new ExpressionBinding[] { new ExpressionBinding("BeforePrint", "Text", "[پایه سنوات]") };
            this.xrLabel94.ExpressionBindings.AddRange(bindingArray3);
            this.xrLabel94.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel94.LocationFloat = new PointFloat(0f, 376.6665f);
            this.xrLabel94.Multiline = true;
            this.xrLabel94.Name = "xrLabel94";
            this.xrLabel94.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel94.SizeF = new SizeF(139.8749f, 27f);
            this.xrLabel94.StylePriority.UseBorders = false;
            this.xrLabel94.StylePriority.UseFont = false;
            this.xrLabel94.StylePriority.UseTextAlignment = false;
            this.xrLabel94.TextAlignment = TextAlignment.MiddleCenter;
            this.xrLabel94.TextFormatString = "{0:###,# ریال}";
            this.xrLabel95.Borders = BorderSide.Top | BorderSide.Left;
            this.xrLabel95.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel95.LocationFloat = new PointFloat(0f, 403.6665f);
            this.xrLabel95.Multiline = true;
            this.xrLabel95.Name = "xrLabel95";
            this.xrLabel95.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel95.SizeF = new SizeF(139.8749f, 27f);
            this.xrLabel95.StylePriority.UseBorders = false;
            this.xrLabel95.StylePriority.UseFont = false;
            this.xrLabel95.StylePriority.UseTextAlignment = false;
            this.xrLabel95.TextAlignment = TextAlignment.MiddleCenter;
            this.xrLabel96.Borders = BorderSide.Top | BorderSide.Left;
            ExpressionBinding[] bindingArray4 = new ExpressionBinding[] { new ExpressionBinding("BeforePrint", "Text", "[حقوق پایه] + [پایه سنوات]") };
            this.xrLabel96.ExpressionBindings.AddRange(bindingArray4);
            this.xrLabel96.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel96.LocationFloat = new PointFloat(0f, 430.5833f);
            this.xrLabel96.Multiline = true;
            this.xrLabel96.Name = "xrLabel96";
            this.xrLabel96.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel96.SizeF = new SizeF(139.8749f, 27.08328f);
            this.xrLabel96.StylePriority.UseBorders = false;
            this.xrLabel96.StylePriority.UseFont = false;
            this.xrLabel96.StylePriority.UseTextAlignment = false;
            this.xrLabel96.TextAlignment = TextAlignment.MiddleCenter;
            this.xrLabel96.TextFormatString = "{0:###,# ریال}";
            this.xrLabel84.Borders = BorderSide.Top | BorderSide.Left;
            ExpressionBinding[] bindingArray5 = new ExpressionBinding[] { new ExpressionBinding("BeforePrint", "Text", "[حقوق پایه] / 30") };
            this.xrLabel84.ExpressionBindings.AddRange(bindingArray5);
            this.xrLabel84.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel84.LocationFloat = new PointFloat(139.8749f, 349.5832f);
            this.xrLabel84.Multiline = true;
            this.xrLabel84.Name = "xrLabel84";
            this.xrLabel84.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel84.SizeF = new SizeF(138.5417f, 27.08325f);
            this.xrLabel84.StylePriority.UseBorders = false;
            this.xrLabel84.StylePriority.UseFont = false;
            this.xrLabel84.StylePriority.UseTextAlignment = false;
            this.xrLabel84.TextAlignment = TextAlignment.MiddleCenter;
            this.xrLabel84.TextFormatString = "{0:###,# ریال}";
            this.xrLabel85.Borders = BorderSide.Top | BorderSide.Left;
            ExpressionBinding[] bindingArray6 = new ExpressionBinding[] { new ExpressionBinding("BeforePrint", "Text", "[پایه سنوات] / 30") };
            this.xrLabel85.ExpressionBindings.AddRange(bindingArray6);
            this.xrLabel85.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel85.LocationFloat = new PointFloat(139.8749f, 376.5833f);
            this.xrLabel85.Multiline = true;
            this.xrLabel85.Name = "xrLabel85";
            this.xrLabel85.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel85.SizeF = new SizeF(138.5417f, 27.08328f);
            this.xrLabel85.StylePriority.UseBorders = false;
            this.xrLabel85.StylePriority.UseFont = false;
            this.xrLabel85.StylePriority.UseTextAlignment = false;
            this.xrLabel85.TextAlignment = TextAlignment.MiddleCenter;
            this.xrLabel85.TextFormatString = "{0:###,# ریال}";
            this.xrLabel86.Borders = BorderSide.Top | BorderSide.Left;
            this.xrLabel86.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel86.LocationFloat = new PointFloat(139.8749f, 403.5833f);
            this.xrLabel86.Multiline = true;
            this.xrLabel86.Name = "xrLabel86";
            this.xrLabel86.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel86.SizeF = new SizeF(138.5417f, 27.08325f);
            this.xrLabel86.StylePriority.UseBorders = false;
            this.xrLabel86.StylePriority.UseFont = false;
            this.xrLabel86.StylePriority.UseTextAlignment = false;
            this.xrLabel86.TextAlignment = TextAlignment.MiddleCenter;
            this.xrLabel87.Borders = BorderSide.Top | BorderSide.Left;
            ExpressionBinding[] bindingArray7 = new ExpressionBinding[] { new ExpressionBinding("BeforePrint", "Text", "([حقوق پایه] + [پایه سنوات]) / 30") };
            this.xrLabel87.ExpressionBindings.AddRange(bindingArray7);
            this.xrLabel87.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel87.LocationFloat = new PointFloat(139.8749f, 430.5833f);
            this.xrLabel87.Multiline = true;
            this.xrLabel87.Name = "xrLabel87";
            this.xrLabel87.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel87.SizeF = new SizeF(138.5417f, 27.08328f);
            this.xrLabel87.StylePriority.UseBorders = false;
            this.xrLabel87.StylePriority.UseFont = false;
            this.xrLabel87.StylePriority.UseTextAlignment = false;
            this.xrLabel87.TextAlignment = TextAlignment.MiddleCenter;
            this.xrLabel87.TextFormatString = "{0:###,# ریال}";
            this.xrLabel88.Borders = BorderSide.Top;
            this.xrLabel88.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel88.LocationFloat = new PointFloat(0f, 457.5834f);
            this.xrLabel88.Multiline = true;
            this.xrLabel88.Name = "xrLabel88";
            this.xrLabel88.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel88.SizeF = new SizeF(278.4166f, 27.08328f);
            this.xrLabel88.StylePriority.UseBorders = false;
            this.xrLabel88.StylePriority.UseFont = false;
            this.xrLabel88.StylePriority.UseTextAlignment = false;
            this.xrLabel88.Text = "ماهانه (سی روزه)";
            this.xrLabel88.TextAlignment = TextAlignment.MiddleCenter;
            this.xrLabel89.Borders = BorderSide.Top;
            ExpressionBinding[] bindingArray8 = new ExpressionBinding[] { new ExpressionBinding("BeforePrint", "Text", "[حق مسکن]") };
            this.xrLabel89.ExpressionBindings.AddRange(bindingArray8);
            this.xrLabel89.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel89.LocationFloat = new PointFloat(0f, 484.5834f);
            this.xrLabel89.Multiline = true;
            this.xrLabel89.Name = "xrLabel89";
            this.xrLabel89.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel89.SizeF = new SizeF(278.4166f, 27.08331f);
            this.xrLabel89.StylePriority.UseBorders = false;
            this.xrLabel89.StylePriority.UseFont = false;
            this.xrLabel89.StylePriority.UseTextAlignment = false;
            this.xrLabel89.TextAlignment = TextAlignment.MiddleCenter;
            this.xrLabel89.TextFormatString = "{0:###,# ریال}";
            this.xrLabel89.BeforePrint += new PrintEventHandler(this.xrLabel89_BeforePrint);
            this.xrLabel90.Borders = BorderSide.Top;
            this.xrLabel90.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel90.LocationFloat = new PointFloat(0f, 511.5834f);
            this.xrLabel90.Multiline = true;
            this.xrLabel90.Name = "xrLabel90";
            this.xrLabel90.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel90.SizeF = new SizeF(278.4166f, 27.08325f);
            this.xrLabel90.StylePriority.UseBorders = false;
            this.xrLabel90.StylePriority.UseFont = false;
            this.xrLabel90.StylePriority.UseTextAlignment = false;
            this.xrLabel90.TextAlignment = TextAlignment.MiddleCenter;
            this.xrLabel91.Borders = BorderSide.Top;
            ExpressionBinding[] bindingArray9 = new ExpressionBinding[] { new ExpressionBinding("BeforePrint", "Text", "[حق اولاد]") };
            this.xrLabel91.ExpressionBindings.AddRange(bindingArray9);
            this.xrLabel91.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel91.LocationFloat = new PointFloat(0.3751121f, 538.5834f);
            this.xrLabel91.Multiline = true;
            this.xrLabel91.Name = "xrLabel91";
            this.xrLabel91.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel91.SizeF = new SizeF(278.4166f, 27.08331f);
            this.xrLabel91.StylePriority.UseBorders = false;
            this.xrLabel91.StylePriority.UseFont = false;
            this.xrLabel91.StylePriority.UseTextAlignment = false;
            this.xrLabel91.TextAlignment = TextAlignment.MiddleCenter;
            this.xrLabel91.TextFormatString = "{0:###,# ریال}";
            this.xrLabel92.Borders = BorderSide.Top;
            ExpressionBinding[] bindingArray10 = new ExpressionBinding[] { new ExpressionBinding("BeforePrint", "Text", "[بن کارگری]") };
            this.xrLabel92.ExpressionBindings.AddRange(bindingArray10);
            this.xrLabel92.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel92.LocationFloat = new PointFloat(0f, 565.5835f);
            this.xrLabel92.Multiline = true;
            this.xrLabel92.Name = "xrLabel92";
            this.xrLabel92.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel92.SizeF = new SizeF(204.0834f, 27.08331f);
            this.xrLabel92.StylePriority.UseBorders = false;
            this.xrLabel92.StylePriority.UseFont = false;
            this.xrLabel92.StylePriority.UseTextAlignment = false;
            this.xrLabel92.TextAlignment = TextAlignment.MiddleCenter;
            this.xrLabel92.TextFormatString = "{0:###,# ریال}";
            ExpressionBinding[] bindingArray11 = new ExpressionBinding[] { new ExpressionBinding("BeforePrint", "Text", "[بن کارگری] +[پایه سنوات]+[حق اولاد]+[حق مسکن]+[حقوق پایه]") };
            this.xrLabel83.ExpressionBindings.AddRange(bindingArray11);
            this.xrLabel83.Font = new Font("B Nazanin", 10f, FontStyle.Bold, GraphicsUnit.Point, 0xb2);
            this.xrLabel83.LocationFloat = new PointFloat(0f, 592.5834f);
            this.xrLabel83.Multiline = true;
            this.xrLabel83.Name = "xrLabel83";
            this.xrLabel83.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel83.SizeF = new SizeF(205.0834f, 105.9166f);
            this.xrLabel83.StylePriority.UseFont = false;
            this.xrLabel83.StylePriority.UseTextAlignment = false;
            this.xrLabel83.TextAlignment = TextAlignment.MiddleCenter;
            this.xrLabel83.TextFormatString = "{0:###,# ریال}";
            this.xrLabel82.Font = new Font("B Nazanin", 10f, FontStyle.Bold, GraphicsUnit.Point, 0xb2);
            this.xrLabel82.LocationFloat = new PointFloat(204.0834f, 592.5834f);
            this.xrLabel82.Multiline = true;
            this.xrLabel82.Name = "xrLabel82";
            this.xrLabel82.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel82.SizeF = new SizeF(208.8859f, 105.9166f);
            this.xrLabel82.StylePriority.UseFont = false;
            this.xrLabel82.Text = "۲۳ - جمع كل مزد و مزایا : ( سی روز )";
            this.xrLabel81.Borders = BorderSide.Top | BorderSide.Left;
            this.xrLabel81.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel81.LocationFloat = new PointFloat(278.4167f, 565.5834f);
            this.xrLabel81.Multiline = true;
            this.xrLabel81.Name = "xrLabel81";
            this.xrLabel81.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel81.SizeF = new SizeF(134.5526f, 27.08337f);
            this.xrLabel81.StylePriority.UseBorders = false;
            this.xrLabel81.StylePriority.UseFont = false;
            this.xrLabel81.Text = "سایر: ";
            this.xrLabel80.Borders = BorderSide.Top | BorderSide.Left;
            this.xrLabel80.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel80.LocationFloat = new PointFloat(278.7917f, 538.5833f);
            this.xrLabel80.Multiline = true;
            this.xrLabel80.Name = "xrLabel80";
            this.xrLabel80.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel80.SizeF = new SizeF(133.5526f, 27.08331f);
            this.xrLabel80.StylePriority.UseBorders = false;
            this.xrLabel80.StylePriority.UseFont = false;
            this.xrLabel80.Text = "عائله مندی (اولاد) :";
            this.xrLabel79.Borders = BorderSide.Top | BorderSide.Left;
            this.xrLabel79.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel79.LocationFloat = new PointFloat(278.4167f, 511.5834f);
            this.xrLabel79.Multiline = true;
            this.xrLabel79.Name = "xrLabel79";
            this.xrLabel79.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel79.SizeF = new SizeF(133.5526f, 27.08325f);
            this.xrLabel79.StylePriority.UseBorders = false;
            this.xrLabel79.StylePriority.UseFont = false;
            this.xrLabel79.Text = "سایر:";
            this.xrLabel78.Borders = BorderSide.Top | BorderSide.Left;
            this.xrLabel78.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel78.LocationFloat = new PointFloat(278.4167f, 484.5833f);
            this.xrLabel78.Multiline = true;
            this.xrLabel78.Name = "xrLabel78";
            this.xrLabel78.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel78.SizeF = new SizeF(133.5526f, 27.08331f);
            this.xrLabel78.StylePriority.UseBorders = false;
            this.xrLabel78.StylePriority.UseFont = false;
            this.xrLabel78.Text = "کمک هزینه‌ی مسکن:";
            this.xrLabel77.Borders = BorderSide.Top | BorderSide.Left;
            this.xrLabel77.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel77.LocationFloat = new PointFloat(278.4167f, 457.5833f);
            this.xrLabel77.Multiline = true;
            this.xrLabel77.Name = "xrLabel77";
            this.xrLabel77.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel77.SizeF = new SizeF(133.5526f, 27.08325f);
            this.xrLabel77.StylePriority.UseBorders = false;
            this.xrLabel77.StylePriority.UseFont = false;
            this.xrLabel77.Text = "۲۲- مزایا";
            this.xrLabel76.Borders = BorderSide.Top | BorderSide.Left;
            this.xrLabel76.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel76.LocationFloat = new PointFloat(278.4167f, 430.5833f);
            this.xrLabel76.Multiline = true;
            this.xrLabel76.Name = "xrLabel76";
            this.xrLabel76.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel76.SizeF = new SizeF(133.5526f, 27.08328f);
            this.xrLabel76.StylePriority.UseBorders = false;
            this.xrLabel76.StylePriority.UseFont = false;
            this.xrLabel76.Text = "جمع مزد مبنای روزانه :";
            this.xrLabel75.Borders = BorderSide.Top | BorderSide.Left;
            this.xrLabel75.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel75.LocationFloat = new PointFloat(278.4167f, 403.5833f);
            this.xrLabel75.Multiline = true;
            this.xrLabel75.Name = "xrLabel75";
            this.xrLabel75.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel75.SizeF = new SizeF(133.5526f, 27.08328f);
            this.xrLabel75.StylePriority.UseBorders = false;
            this.xrLabel75.StylePriority.UseFont = false;
            this.xrLabel75.Text = "سایر:";
            this.xrLabel74.Borders = BorderSide.Top | BorderSide.Left;
            this.xrLabel74.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel74.LocationFloat = new PointFloat(278.4167f, 376.5832f);
            this.xrLabel74.Multiline = true;
            this.xrLabel74.Name = "xrLabel74";
            this.xrLabel74.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel74.SizeF = new SizeF(133.5526f, 27.08328f);
            this.xrLabel74.StylePriority.UseBorders = false;
            this.xrLabel74.StylePriority.UseFont = false;
            this.xrLabel74.Text = "مزد سنوات :";
            this.xrLabel73.Borders = BorderSide.Top | BorderSide.Left;
            this.xrLabel73.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel73.LocationFloat = new PointFloat(278.4167f, 349.5832f);
            this.xrLabel73.Multiline = true;
            this.xrLabel73.Name = "xrLabel73";
            this.xrLabel73.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel73.SizeF = new SizeF(133.5526f, 27.08334f);
            this.xrLabel73.StylePriority.UseBorders = false;
            this.xrLabel73.StylePriority.UseFont = false;
            this.xrLabel73.Text = "مزد گروه (مزد شغل):";
            this.xrLabel70.Borders = BorderSide.Top | BorderSide.Left;
            this.xrLabel70.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel70.LocationFloat = new PointFloat(278.4167f, 322.5832f);
            this.xrLabel70.Multiline = true;
            this.xrLabel70.Name = "xrLabel70";
            this.xrLabel70.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel70.SizeF = new SizeF(133.5526f, 27.08328f);
            this.xrLabel70.StylePriority.UseBorders = false;
            this.xrLabel70.StylePriority.UseFont = false;
            this.xrLabel70.Text = "21- مزد مبنا";
            this.xrLabel71.Borders = BorderSide.Top | BorderSide.Left;
            this.xrLabel71.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel71.LocationFloat = new PointFloat(139.8749f, 322.5831f);
            this.xrLabel71.Multiline = true;
            this.xrLabel71.Name = "xrLabel71";
            this.xrLabel71.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel71.SizeF = new SizeF(138.5417f, 27.08328f);
            this.xrLabel71.StylePriority.UseBorders = false;
            this.xrLabel71.StylePriority.UseFont = false;
            this.xrLabel71.StylePriority.UseTextAlignment = false;
            this.xrLabel71.Text = "روزانه";
            this.xrLabel71.TextAlignment = TextAlignment.MiddleCenter;
            this.xrLabel72.Borders = BorderSide.Top | BorderSide.Left;
            this.xrLabel72.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel72.LocationFloat = new PointFloat(0f, 322.6664f);
            this.xrLabel72.Multiline = true;
            this.xrLabel72.Name = "xrLabel72";
            this.xrLabel72.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel72.SizeF = new SizeF(139.8749f, 27f);
            this.xrLabel72.StylePriority.UseBorders = false;
            this.xrLabel72.StylePriority.UseFont = false;
            this.xrLabel72.StylePriority.UseTextAlignment = false;
            this.xrLabel72.Text = "ماهانه";
            this.xrLabel72.TextAlignment = TextAlignment.MiddleCenter;
            this.xrLabel69.Borders = BorderSide.Top | BorderSide.Left;
            this.xrLabel69.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel69.LocationFloat = new PointFloat(412.3444f, 592.5834f);
            this.xrLabel69.Multiline = true;
            this.xrLabel69.Name = "xrLabel69";
            this.xrLabel69.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel69.SizeF = new SizeF(330.4891f, 104.9167f);
            this.xrLabel69.StylePriority.UseBorders = false;
            this.xrLabel69.StylePriority.UseFont = false;
            this.xrLabel69.Text = "حق شبکاری بر اساس زمان کارکرد در محدوده کاری شب محاسبه و پرداخت میگردد مبلغ دستمزد شما بر اساس سال 97 ثبت شده ، بدیهی است حقوق و مزایای شما طبق مصوبه شورای عالی كار در سال 98 تطبیق و پرداخت خواهد شد";
            this.xrLabel68.Borders = BorderSide.Top | BorderSide.Left;
            this.xrLabel68.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel68.LocationFloat = new PointFloat(412.3444f, 538.5833f);
            this.xrLabel68.Multiline = true;
            this.xrLabel68.Name = "xrLabel68";
            this.xrLabel68.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel68.SizeF = new SizeF(330.8641f, 54.08337f);
            this.xrLabel68.StylePriority.UseBorders = false;
            this.xrLabel68.StylePriority.UseFont = false;
            this.xrLabel68.Text = "حقوق  و  مزایای  شما  در  اجرای  ماده  39  قانون  كار  بر  اساس \r\n(44) ساعت در هفته قید شده است .";
            this.xrLabel67.Borders = BorderSide.Top | BorderSide.Left;
            this.xrLabel67.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel67.LocationFloat = new PointFloat(411.9694f, 484.6667f);
            this.xrLabel67.Multiline = true;
            this.xrLabel67.Name = "xrLabel67";
            this.xrLabel67.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel67.SizeF = new SizeF(330.8641f, 53.99994f);
            this.xrLabel67.StylePriority.UseBorders = false;
            this.xrLabel67.StylePriority.UseFont = false;
            this.xrLabel67.Text = "25- مواردی كه در این قرارداد پیش بینی نشده است تابع قوانین كار\r\nو تامین اجتماعی است .";
            this.xrLabel66.Borders = BorderSide.Left;
            this.xrLabel66.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel66.LocationFloat = new PointFloat(411.9694f, 401.6664f);
            this.xrLabel66.Multiline = true;
            this.xrLabel66.Name = "xrLabel66";
            this.xrLabel66.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel66.SizeF = new SizeF(330.8641f, 83.00027f);
            this.xrLabel66.StylePriority.UseBorders = false;
            this.xrLabel66.StylePriority.UseFont = false;
            this.xrLabel66.Text = "بر اساس شرح وظایف مصوب شغل مربوط مندرج در طرح هماهنگ \r\nطبقه بندی مشاغل كه این  وظایف را در واحد  محل خدمت  موضوع\r\nبند 19 این قرارداد تحت نظارت انجام میدهد .";
            this.xrLabel65.Borders = BorderSide.Left;
            ExpressionBinding[] bindingArray12 = new ExpressionBinding[] { new ExpressionBinding("BeforePrint", "Text", "[شغل]") };
            this.xrLabel65.ExpressionBindings.AddRange(bindingArray12);
            this.xrLabel65.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel65.LocationFloat = new PointFloat(411.9693f, 374.5832f);
            this.xrLabel65.Multiline = true;
            this.xrLabel65.Name = "xrLabel65";
            this.xrLabel65.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel65.SizeF = new SizeF(329.2391f, 27.08334f);
            this.xrLabel65.StylePriority.UseBorders = false;
            this.xrLabel65.StylePriority.UseFont = false;
            this.xrLabel65.StylePriority.UseTextAlignment = false;
            this.xrLabel65.TextAlignment = TextAlignment.MiddleCenter;
            this.xrLabel64.Borders = BorderSide.Top | BorderSide.Left;
            this.xrLabel64.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel64.LocationFloat = new PointFloat(411.9693f, 322.5832f);
            this.xrLabel64.Multiline = true;
            this.xrLabel64.Name = "xrLabel64";
            this.xrLabel64.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel64.SizeF = new SizeF(330.8641f, 52.08328f);
            this.xrLabel64.StylePriority.UseBorders = false;
            this.xrLabel64.StylePriority.UseFont = false;
            this.xrLabel64.Text = "24- شرح قرارداد و شرح وظایف كلی كارگر :\r\nوظیفه كارگر در این قرارداد عبارت است از انجام امور مربوط به \r\n";
            this.xrLabel63.Borders = BorderSide.Top | BorderSide.Left;
            this.xrLabel63.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel63.LocationFloat = new PointFloat(0f, 295.6665f);
            this.xrLabel63.Multiline = true;
            this.xrLabel63.Name = "xrLabel63";
            this.xrLabel63.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel63.SizeF = new SizeF(663.7086f, 27f);
            this.xrLabel63.StylePriority.UseBorders = false;
            this.xrLabel63.StylePriority.UseFont = false;
            this.xrLabel63.StylePriority.UseTextAlignment = false;
            this.xrLabel63.Text = "        جمعه (با رعایت ماده 62 قانون كار )";
            this.xrLabel63.TextAlignment = TextAlignment.MiddleLeft;
            this.xrLabel62.Borders = BorderSide.Top;
            this.xrLabel62.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel62.LocationFloat = new PointFloat(660.5416f, 295.6664f);
            this.xrLabel62.Multiline = true;
            this.xrLabel62.Name = "xrLabel62";
            this.xrLabel62.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel62.SizeF = new SizeF(80.66681f, 27f);
            this.xrLabel62.StylePriority.UseBorders = false;
            this.xrLabel62.StylePriority.UseFont = false;
            this.xrLabel62.Text = "تعطیل هفتگی ";
            this.xrLabel61.Borders = BorderSide.None;
            this.xrLabel61.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel61.LocationFloat = new PointFloat(1.833216f, 269f);
            this.xrLabel61.Multiline = true;
            this.xrLabel61.Name = "xrLabel61";
            this.xrLabel61.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel61.SizeF = new SizeF(304.3751f, 27f);
            this.xrLabel61.StylePriority.UseBorders = false;
            this.xrLabel61.StylePriority.UseFont = false;
            this.xrLabel61.Text = "جمعا (44) ساعت در هفته (با رعایت مواد 51 الی 61 قانون كار)";
            this.xrLabel59.Borders = BorderSide.None;
            this.xrLabel59.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel59.LocationFloat = new PointFloat(459f, 269f);
            this.xrLabel59.Multiline = true;
            this.xrLabel59.Name = "xrLabel59";
            this.xrLabel59.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel59.SizeF = new SizeF(53.0835f, 27f);
            this.xrLabel59.StylePriority.UseBorders = false;
            this.xrLabel59.StylePriority.UseFont = false;
            this.xrLabel59.Text = "تا ساعت ";
            this.xrLabel60.Borders = BorderSide.None;
            ExpressionBinding[] bindingArray13 = new ExpressionBinding[] { new ExpressionBinding("BeforePrint", "Text", "[ساعت پایان کار]") };
            this.xrLabel60.ExpressionBindings.AddRange(bindingArray13);
            this.xrLabel60.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel60.LocationFloat = new PointFloat(306.2084f, 269f);
            this.xrLabel60.Multiline = true;
            this.xrLabel60.Name = "xrLabel60";
            this.xrLabel60.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel60.SizeF = new SizeF(153.2917f, 27f);
            this.xrLabel60.StylePriority.UseBorders = false;
            this.xrLabel60.StylePriority.UseFont = false;
            this.xrLabel60.StylePriority.UseTextAlignment = false;
            this.xrLabel60.Text = "-";
            this.xrLabel60.TextAlignment = TextAlignment.MiddleCenter;
            this.xrLabel57.Borders = BorderSide.None;
            this.xrLabel57.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel57.LocationFloat = new PointFloat(617.8334f, 269f);
            this.xrLabel57.Multiline = true;
            this.xrLabel57.Name = "xrLabel57";
            this.xrLabel57.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel57.SizeF = new SizeF(125f, 27f);
            this.xrLabel57.StylePriority.UseBorders = false;
            this.xrLabel57.StylePriority.UseFont = false;
            this.xrLabel57.Text = "ساعت اداری کار از ساعت";
            this.xrLabel58.Borders = BorderSide.None;
            ExpressionBinding[] bindingArray14 = new ExpressionBinding[] { new ExpressionBinding("BeforePrint", "Text", "[ساعت شروع کار]") };
            this.xrLabel58.ExpressionBindings.AddRange(bindingArray14);
            this.xrLabel58.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel58.LocationFloat = new PointFloat(511.5836f, 269f);
            this.xrLabel58.Multiline = true;
            this.xrLabel58.Name = "xrLabel58";
            this.xrLabel58.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel58.SizeF = new SizeF(107.2084f, 27f);
            this.xrLabel58.StylePriority.UseBorders = false;
            this.xrLabel58.StylePriority.UseFont = false;
            this.xrLabel58.StylePriority.UseTextAlignment = false;
            this.xrLabel58.Text = "-";
            this.xrLabel58.TextAlignment = TextAlignment.MiddleCenter;
            this.xrLabel55.Borders = BorderSide.Top;
            this.xrLabel55.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel55.LocationFloat = new PointFloat(79.45824f, 242f);
            this.xrLabel55.Multiline = true;
            this.xrLabel55.Name = "xrLabel55";
            this.xrLabel55.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel55.SizeF = new SizeF(42f, 27f);
            this.xrLabel55.StylePriority.UseBorders = false;
            this.xrLabel55.StylePriority.UseFont = false;
            this.xrLabel55.Text = "به مدت";
            this.xrLabel53.Borders = BorderSide.Top;
            this.xrLabel53.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel53.LocationFloat = new PointFloat(250.0001f, 242f);
            this.xrLabel53.Multiline = true;
            this.xrLabel53.Name = "xrLabel53";
            this.xrLabel53.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel53.SizeF = new SizeF(80.29162f, 27f);
            this.xrLabel53.StylePriority.UseBorders = false;
            this.xrLabel53.StylePriority.UseFont = false;
            this.xrLabel53.Text = "تا تاریخ ";
            this.xrLabel54.Borders = BorderSide.Top;
            this.xrLabel54.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel54.LocationFloat = new PointFloat(121.1249f, 242f);
            this.xrLabel54.Multiline = true;
            this.xrLabel54.Name = "xrLabel54";
            this.xrLabel54.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel54.SizeF = new SizeF(128.8752f, 27f);
            this.xrLabel54.StylePriority.UseBorders = false;
            this.xrLabel54.StylePriority.UseFont = false;
            this.xrLabel54.StylePriority.UseTextAlignment = false;
            this.xrLabel54.TextAlignment = TextAlignment.MiddleCenter;
            this.xrLabel52.Borders = BorderSide.Top;
            this.xrLabel52.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel52.LocationFloat = new PointFloat(330.2916f, 242f);
            this.xrLabel52.Multiline = true;
            this.xrLabel52.Name = "xrLabel52";
            this.xrLabel52.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel52.SizeF = new SizeF(144.8334f, 27f);
            this.xrLabel52.StylePriority.UseBorders = false;
            this.xrLabel52.StylePriority.UseFont = false;
            this.xrLabel52.StylePriority.UseTextAlignment = false;
            this.xrLabel52.TextAlignment = TextAlignment.MiddleCenter;
            this.xrLabel51.Borders = BorderSide.Top;
            this.xrLabel51.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel51.LocationFloat = new PointFloat(475.125f, 242f);
            this.xrLabel51.Multiline = true;
            this.xrLabel51.Name = "xrLabel51";
            this.xrLabel51.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel51.SizeF = new SizeF(126.5415f, 27f);
            this.xrLabel51.StylePriority.UseBorders = false;
            this.xrLabel51.StylePriority.UseFont = false;
            this.xrLabel51.Text = "مدت قرار داد از تاریخ";
            this.xrLabel49.Borders = BorderSide.Top;
            this.xrLabel49.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel49.LocationFloat = new PointFloat(601.6666f, 242f);
            this.xrLabel49.Multiline = true;
            this.xrLabel49.Name = "xrLabel49";
            this.xrLabel49.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel49.SizeF = new SizeF(140.3334f, 27f);
            this.xrLabel49.StylePriority.UseBorders = false;
            this.xrLabel49.StylePriority.UseFont = false;
            this.xrLabel49.Text = "۲۰ - ساعت و مدت قرارداد";
            this.xrLabel47.Borders = BorderSide.Top;
            this.xrLabel47.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel47.LocationFloat = new PointFloat(575.1252f, 215.3332f);
            this.xrLabel47.Multiline = true;
            this.xrLabel47.Name = "xrLabel47";
            this.xrLabel47.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel47.SizeF = new SizeF(71.87488f, 27f);
            this.xrLabel47.StylePriority.UseBorders = false;
            this.xrLabel47.StylePriority.UseFont = false;
            this.xrLabel47.Text = "نشانی کامل : ";
            this.xrLabel48.Borders = BorderSide.Top | BorderSide.Left;
            ExpressionBinding[] bindingArray15 = new ExpressionBinding[] { new ExpressionBinding("BeforePrint", "Text", "[نشانی واحد یا سازمان محل خدمت]") };
            this.xrLabel48.ExpressionBindings.AddRange(bindingArray15);
            this.xrLabel48.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel48.LocationFloat = new PointFloat(0f, 215.3332f);
            this.xrLabel48.Multiline = true;
            this.xrLabel48.Name = "xrLabel48";
            this.xrLabel48.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel48.SizeF = new SizeF(575.2919f, 26.99997f);
            this.xrLabel48.StylePriority.UseBorders = false;
            this.xrLabel48.StylePriority.UseFont = false;
            this.xrLabel48.StylePriority.UseTextAlignment = false;
            this.xrLabel48.TextAlignment = TextAlignment.MiddleCenter;
            this.xrLabel45.Borders = BorderSide.Top;
            this.xrLabel45.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel45.LocationFloat = new PointFloat(105.3333f, 188.3332f);
            this.xrLabel45.Multiline = true;
            this.xrLabel45.Name = "xrLabel45";
            this.xrLabel45.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel45.SizeF = new SizeF(86.25005f, 26.99998f);
            this.xrLabel45.StylePriority.UseBorders = false;
            this.xrLabel45.StylePriority.UseFont = false;
            this.xrLabel45.Text = "۲۰- به مدیریت :";
            this.xrLabel46.Borders = BorderSide.Top | BorderSide.Left;
            ExpressionBinding[] bindingArray16 = new ExpressionBinding[] { new ExpressionBinding("BeforePrint", "Text", "[مدیریت واحد یا سازمان محل خدمت]") };
            this.xrLabel46.ExpressionBindings.AddRange(bindingArray16);
            this.xrLabel46.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel46.LocationFloat = new PointFloat(0f, 188.3335f);
            this.xrLabel46.Multiline = true;
            this.xrLabel46.Name = "xrLabel46";
            this.xrLabel46.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel46.SizeF = new SizeF(105.3333f, 26.99997f);
            this.xrLabel46.StylePriority.UseBorders = false;
            this.xrLabel46.StylePriority.UseFont = false;
            this.xrLabel46.StylePriority.UseTextAlignment = false;
            this.xrLabel46.TextAlignment = TextAlignment.MiddleCenter;
            this.xrLabel43.Borders = BorderSide.Top;
            this.xrLabel43.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel43.LocationFloat = new PointFloat(459f, 188.3332f);
            this.xrLabel43.Multiline = true;
            this.xrLabel43.Name = "xrLabel43";
            this.xrLabel43.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel43.SizeF = new SizeF(188.0001f, 26.99998f);
            this.xrLabel43.StylePriority.UseBorders = false;
            this.xrLabel43.StylePriority.UseFont = false;
            this.xrLabel43.Text = "۱۹- نام واحد یا سازمان محل خدمت :";
            this.xrLabel44.Borders = BorderSide.Top | BorderSide.Left;
            ExpressionBinding[] bindingArray17 = new ExpressionBinding[] { new ExpressionBinding("BeforePrint", "Text", "[نام واحد یا سازمان محل خدمت]") };
            this.xrLabel44.ExpressionBindings.AddRange(bindingArray17);
            this.xrLabel44.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel44.LocationFloat = new PointFloat(191.5835f, 188.3332f);
            this.xrLabel44.Multiline = true;
            this.xrLabel44.Name = "xrLabel44";
            this.xrLabel44.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel44.SizeF = new SizeF(267.9166f, 26.99998f);
            this.xrLabel44.StylePriority.UseBorders = false;
            this.xrLabel44.StylePriority.UseFont = false;
            this.xrLabel44.StylePriority.UseTextAlignment = false;
            this.xrLabel44.TextAlignment = TextAlignment.MiddleCenter;
            this.xrLabel42.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel42.LocationFloat = new PointFloat(647.0001f, 188f);
            this.xrLabel42.Multiline = true;
            this.xrLabel42.Name = "xrLabel42";
            this.xrLabel42.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel42.SizeF = new SizeF(95.83331f, 55.33328f);
            this.xrLabel42.StylePriority.UseFont = false;
            this.xrLabel42.Text = "د) مشخصات کارفرمای پیمانکار";
            this.xrLabel40.Borders = BorderSide.Top;
            this.xrLabel40.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel40.LocationFloat = new PointFloat(91.83324f, 161.3334f);
            this.xrLabel40.Multiline = true;
            this.xrLabel40.Name = "xrLabel40";
            this.xrLabel40.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel40.SizeF = new SizeF(80.20834f, 27f);
            this.xrLabel40.StylePriority.UseBorders = false;
            this.xrLabel40.StylePriority.UseFont = false;
            this.xrLabel40.Text = "۱۸- گروه شغل :";
            this.xrLabel41.Borders = BorderSide.Top | BorderSide.Left;
            ExpressionBinding[] bindingArray18 = new ExpressionBinding[] { new ExpressionBinding("BeforePrint", "Text", "[کد گروه شغل]") };
            this.xrLabel41.ExpressionBindings.AddRange(bindingArray18);
            this.xrLabel41.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel41.LocationFloat = new PointFloat(0f, 161.3334f);
            this.xrLabel41.Multiline = true;
            this.xrLabel41.Name = "xrLabel41";
            this.xrLabel41.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel41.SizeF = new SizeF(91.83324f, 27f);
            this.xrLabel41.StylePriority.UseBorders = false;
            this.xrLabel41.StylePriority.UseFont = false;
            this.xrLabel41.StylePriority.UseTextAlignment = false;
            this.xrLabel41.TextAlignment = TextAlignment.MiddleCenter;
            this.xrLabel38.Borders = BorderSide.Top;
            this.xrLabel38.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel38.LocationFloat = new PointFloat(248f, 161.3332f);
            this.xrLabel38.Multiline = true;
            this.xrLabel38.Name = "xrLabel38";
            this.xrLabel38.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel38.SizeF = new SizeF(82.29167f, 27f);
            this.xrLabel38.StylePriority.UseBorders = false;
            this.xrLabel38.StylePriority.UseFont = false;
            this.xrLabel38.Text = "۱۷- کد شغل :";
            this.xrLabel39.Borders = BorderSide.Top | BorderSide.Left;
            this.xrLabel39.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel39.LocationFloat = new PointFloat(172.0416f, 161.3332f);
            this.xrLabel39.Multiline = true;
            this.xrLabel39.Name = "xrLabel39";
            this.xrLabel39.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel39.SizeF = new SizeF(75.95837f, 27f);
            this.xrLabel39.StylePriority.UseBorders = false;
            this.xrLabel39.StylePriority.UseFont = false;
            this.xrLabel39.StylePriority.UseTextAlignment = false;
            this.xrLabel39.TextAlignment = TextAlignment.MiddleCenter;
            this.xrLabel36.Borders = BorderSide.Top;
            this.xrLabel36.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel36.LocationFloat = new PointFloat(522.0002f, 161.3332f);
            this.xrLabel36.Multiline = true;
            this.xrLabel36.Name = "xrLabel36";
            this.xrLabel36.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel36.SizeF = new SizeF(124.9998f, 27f);
            this.xrLabel36.StylePriority.UseBorders = false;
            this.xrLabel36.StylePriority.UseFont = false;
            this.xrLabel36.Text = "۱۶-عنوان شغل کارگر";
            this.xrLabel37.Borders = BorderSide.Top | BorderSide.Left;
            ExpressionBinding[] bindingArray19 = new ExpressionBinding[] { new ExpressionBinding("BeforePrint", "Text", "[شغل]") };
            this.xrLabel37.ExpressionBindings.AddRange(bindingArray19);
            this.xrLabel37.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel37.LocationFloat = new PointFloat(330.2916f, 161.3332f);
            this.xrLabel37.Multiline = true;
            this.xrLabel37.Name = "xrLabel37";
            this.xrLabel37.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel37.SizeF = new SizeF(191.7086f, 27f);
            this.xrLabel37.StylePriority.UseBorders = false;
            this.xrLabel37.StylePriority.UseFont = false;
            this.xrLabel37.StylePriority.UseTextAlignment = false;
            this.xrLabel37.TextAlignment = TextAlignment.MiddleCenter;
            this.xrLabel35.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel35.LocationFloat = new PointFloat(647.0001f, 161.3332f);
            this.xrLabel35.Multiline = true;
            this.xrLabel35.Name = "xrLabel35";
            this.xrLabel35.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel35.SizeF = new SizeF(95.83331f, 28f);
            this.xrLabel35.StylePriority.UseFont = false;
            this.xrLabel35.Text = "ج) مشخصات شغل";
            this.xrLabel31.Borders = BorderSide.Top;
            this.xrLabel31.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel31.LocationFloat = new PointFloat(562.5419f, 134.3333f);
            this.xrLabel31.Multiline = true;
            this.xrLabel31.Name = "xrLabel31";
            this.xrLabel31.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel31.SizeF = new SizeF(97.99976f, 27f);
            this.xrLabel31.StylePriority.UseBorders = false;
            this.xrLabel31.StylePriority.UseFont = false;
            this.xrLabel31.Text = "14- نشانی شرکت :";
            this.xrLabel32.Borders = BorderSide.Top | BorderSide.Left;
            ExpressionBinding[] bindingArray20 = new ExpressionBinding[] { new ExpressionBinding("BeforePrint", "Text", "[address]") };
            this.xrLabel32.ExpressionBindings.AddRange(bindingArray20);
            this.xrLabel32.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel32.LocationFloat = new PointFloat(204.0834f, 134.3334f);
            this.xrLabel32.Multiline = true;
            this.xrLabel32.Name = "xrLabel32";
            this.xrLabel32.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel32.SizeF = new SizeF(358.4585f, 27f);
            this.xrLabel32.StylePriority.UseBorders = false;
            this.xrLabel32.StylePriority.UseFont = false;
            this.xrLabel32.StylePriority.UseTextAlignment = false;
            this.xrLabel32.TextAlignment = TextAlignment.MiddleCenter;
            this.xrLabel33.Borders = BorderSide.Top;
            this.xrLabel33.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel33.LocationFloat = new PointFloat(119.7084f, 134.3332f);
            this.xrLabel33.Multiline = true;
            this.xrLabel33.Name = "xrLabel33";
            this.xrLabel33.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel33.SizeF = new SizeF(84.37499f, 27f);
            this.xrLabel33.StylePriority.UseBorders = false;
            this.xrLabel33.StylePriority.UseFont = false;
            this.xrLabel33.Text = "۱۵- شماره ثبت :";
            this.xrLabel34.Borders = BorderSide.Top | BorderSide.Left;
            ExpressionBinding[] bindingArray21 = new ExpressionBinding[] { new ExpressionBinding("BeforePrint", "Text", "[register_number]") };
            this.xrLabel34.ExpressionBindings.AddRange(bindingArray21);
            this.xrLabel34.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel34.LocationFloat = new PointFloat(0f, 134.3332f);
            this.xrLabel34.Multiline = true;
            this.xrLabel34.Name = "xrLabel34";
            this.xrLabel34.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel34.SizeF = new SizeF(119.7084f, 27f);
            this.xrLabel34.StylePriority.UseBorders = false;
            this.xrLabel34.StylePriority.UseFont = false;
            this.xrLabel34.StylePriority.UseTextAlignment = false;
            this.xrLabel34.TextAlignment = TextAlignment.MiddleCenter;
            this.xrLabel25.Borders = BorderSide.Top;
            this.xrLabel25.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel25.LocationFloat = new PointFloat(562.5416f, 107f);
            this.xrLabel25.Multiline = true;
            this.xrLabel25.Name = "xrLabel25";
            this.xrLabel25.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel25.SizeF = new SizeF(98.00006f, 27.33322f);
            this.xrLabel25.StylePriority.UseBorders = false;
            this.xrLabel25.StylePriority.UseFont = false;
            this.xrLabel25.Text = "۱۲- نام شرکت :";
            this.xrLabel28.Borders = BorderSide.Top | BorderSide.Left;
            ExpressionBinding[] bindingArray22 = new ExpressionBinding[] { new ExpressionBinding("BeforePrint", "Text", "[company_name]") };
            this.xrLabel28.ExpressionBindings.AddRange(bindingArray22);
            this.xrLabel28.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel28.LocationFloat = new PointFloat(264.8749f, 107.0001f);
            this.xrLabel28.Multiline = true;
            this.xrLabel28.Name = "xrLabel28";
            this.xrLabel28.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel28.SizeF = new SizeF(297.6667f, 27.33312f);
            this.xrLabel28.StylePriority.UseBorders = false;
            this.xrLabel28.StylePriority.UseFont = false;
            this.xrLabel28.StylePriority.UseTextAlignment = false;
            this.xrLabel28.TextAlignment = TextAlignment.MiddleCenter;
            this.xrLabel29.Borders = BorderSide.Top;
            this.xrLabel29.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel29.LocationFloat = new PointFloat(139.8749f, 107.0001f);
            this.xrLabel29.Multiline = true;
            this.xrLabel29.Name = "xrLabel29";
            this.xrLabel29.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel29.SizeF = new SizeF(125f, 27.33312f);
            this.xrLabel29.StylePriority.UseBorders = false;
            this.xrLabel29.StylePriority.UseFont = false;
            this.xrLabel29.Text = "۱۳- مدیرعامل :";
            this.xrLabel30.Borders = BorderSide.Top | BorderSide.Left;
            ExpressionBinding[] bindingArray23 = new ExpressionBinding[] { new ExpressionBinding("BeforePrint", "Text", "[ceo_name]") };
            this.xrLabel30.ExpressionBindings.AddRange(bindingArray23);
            this.xrLabel30.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel30.LocationFloat = new PointFloat(0f, 107.0001f);
            this.xrLabel30.Multiline = true;
            this.xrLabel30.Name = "xrLabel30";
            this.xrLabel30.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel30.SizeF = new SizeF(139.8749f, 27.33312f);
            this.xrLabel30.StylePriority.UseBorders = false;
            this.xrLabel30.StylePriority.UseFont = false;
            this.xrLabel30.StylePriority.UseTextAlignment = false;
            this.xrLabel30.TextAlignment = TextAlignment.MiddleCenter;
            this.xrLabel24.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel24.LocationFloat = new PointFloat(660.5416f, 107f);
            this.xrLabel24.Multiline = true;
            this.xrLabel24.Name = "xrLabel24";
            this.xrLabel24.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel24.SizeF = new SizeF(82.29169f, 55.33328f);
            this.xrLabel24.StylePriority.UseFont = false;
            this.xrLabel24.Text = "ب) مشخصات پیمانکار";
            this.xrLabel22.Borders = BorderSide.Top;
            this.xrLabel22.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel22.LocationFloat = new PointFloat(475.125f, 80.99997f);
            this.xrLabel22.Multiline = true;
            this.xrLabel22.Name = "xrLabel22";
            this.xrLabel22.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel22.SizeF = new SizeF(185.4167f, 27f);
            this.xrLabel22.StylePriority.UseBorders = false;
            this.xrLabel22.StylePriority.UseFont = false;
            this.xrLabel22.Text = "۱۰- آخرین مدرک و وضعیت تحصیلی :";
            this.xrLabel23.Borders = BorderSide.Top | BorderSide.Left;
            ExpressionBinding[] bindingArray24 = new ExpressionBinding[] { new ExpressionBinding("BeforePrint", "Text", "[آخرین مدرک و رشته تحصیلی]") };
            this.xrLabel23.ExpressionBindings.AddRange(bindingArray24);
            this.xrLabel23.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel23.LocationFloat = new PointFloat(244.7083f, 81.00003f);
            this.xrLabel23.Multiline = true;
            this.xrLabel23.Name = "xrLabel23";
            this.xrLabel23.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel23.SizeF = new SizeF(230.4167f, 26.99994f);
            this.xrLabel23.StylePriority.UseBorders = false;
            this.xrLabel23.StylePriority.UseFont = false;
            this.xrLabel23.StylePriority.UseTextAlignment = false;
            this.xrLabel23.TextAlignment = TextAlignment.MiddleCenter;
            this.xrLabel26.Borders = BorderSide.Top;
            this.xrLabel26.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel26.LocationFloat = new PointFloat(117.7083f, 80.99997f);
            this.xrLabel26.Multiline = true;
            this.xrLabel26.Name = "xrLabel26";
            this.xrLabel26.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel26.SizeF = new SizeF(127.2917f, 26.00012f);
            this.xrLabel26.StylePriority.UseBorders = false;
            this.xrLabel26.StylePriority.UseFont = false;
            this.xrLabel26.Text = "۱۱- شماره پرسنلی :";
            this.xrLabel27.Borders = BorderSide.Top | BorderSide.Left;
            ExpressionBinding[] bindingArray25 = new ExpressionBinding[] { new ExpressionBinding("BeforePrint", "Text", "[کد پرسنلی]") };
            this.xrLabel27.ExpressionBindings.AddRange(bindingArray25);
            this.xrLabel27.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel27.LocationFloat = new PointFloat(0f, 81.00003f);
            this.xrLabel27.Multiline = true;
            this.xrLabel27.Name = "xrLabel27";
            this.xrLabel27.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel27.SizeF = new SizeF(117.7083f, 26.00006f);
            this.xrLabel27.StylePriority.UseBorders = false;
            this.xrLabel27.StylePriority.UseFont = false;
            this.xrLabel27.StylePriority.UseTextAlignment = false;
            this.xrLabel27.TextAlignment = TextAlignment.MiddleCenter;
            this.xrLabel16.Borders = BorderSide.Top;
            this.xrLabel16.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel16.LocationFloat = new PointFloat(562.5419f, 54f);
            this.xrLabel16.Multiline = true;
            this.xrLabel16.Name = "xrLabel16";
            this.xrLabel16.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel16.SizeF = new SizeF(98.00006f, 27.00001f);
            this.xrLabel16.StylePriority.UseBorders = false;
            this.xrLabel16.StylePriority.UseFont = false;
            this.xrLabel16.Text = "۷- وضعیت تاهل :";
            this.xrLabel17.Borders = BorderSide.Top | BorderSide.Left;
            ExpressionBinding[] bindingArray26 = new ExpressionBinding[] { new ExpressionBinding("BeforePrint", "Text", "Iif([تعداد اولاد] > 0, 'متاهل' , 'مجرد')") };
            this.xrLabel17.ExpressionBindings.AddRange(bindingArray26);
            this.xrLabel17.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel17.LocationFloat = new PointFloat(428.4166f, 54f);
            this.xrLabel17.Multiline = true;
            this.xrLabel17.Name = "xrLabel17";
            this.xrLabel17.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel17.SizeF = new SizeF(134.125f, 27.00001f);
            this.xrLabel17.StylePriority.UseBorders = false;
            this.xrLabel17.StylePriority.UseFont = false;
            this.xrLabel17.StylePriority.UseTextAlignment = false;
            this.xrLabel17.TextAlignment = TextAlignment.MiddleCenter;
            this.xrLabel18.Borders = BorderSide.Top;
            this.xrLabel18.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel18.LocationFloat = new PointFloat(351.3332f, 54f);
            this.xrLabel18.Multiline = true;
            this.xrLabel18.Name = "xrLabel18";
            this.xrLabel18.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel18.SizeF = new SizeF(77.08331f, 27f);
            this.xrLabel18.StylePriority.UseBorders = false;
            this.xrLabel18.StylePriority.UseFont = false;
            this.xrLabel18.Text = "۸- تعداد اولاد:";
            this.xrLabel19.Borders = BorderSide.Top | BorderSide.Left;
            ExpressionBinding[] bindingArray27 = new ExpressionBinding[] { new ExpressionBinding("BeforePrint", "Text", "[تعداد اولاد]") };
            this.xrLabel19.ExpressionBindings.AddRange(bindingArray27);
            this.xrLabel19.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel19.LocationFloat = new PointFloat(244.7083f, 54f);
            this.xrLabel19.Multiline = true;
            this.xrLabel19.Name = "xrLabel19";
            this.xrLabel19.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel19.SizeF = new SizeF(106.6249f, 27.00001f);
            this.xrLabel19.StylePriority.UseBorders = false;
            this.xrLabel19.StylePriority.UseFont = false;
            this.xrLabel19.StylePriority.UseTextAlignment = false;
            this.xrLabel19.Text = "\r\n";
            this.xrLabel19.TextAlignment = TextAlignment.MiddleCenter;
            this.xrLabel20.Borders = BorderSide.Top;
            this.xrLabel20.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel20.LocationFloat = new PointFloat(117.7083f, 54.00003f);
            this.xrLabel20.Multiline = true;
            this.xrLabel20.Name = "xrLabel20";
            this.xrLabel20.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel20.SizeF = new SizeF(127f, 27f);
            this.xrLabel20.StylePriority.UseBorders = false;
            this.xrLabel20.StylePriority.UseFont = false;
            this.xrLabel20.Text = "۹- وضعیت سربازی :";
            this.xrLabel21.Borders = BorderSide.Top | BorderSide.Left;
            ExpressionBinding[] bindingArray28 = new ExpressionBinding[] { new ExpressionBinding("BeforePrint", "Text", "[وضعیت سربازی]") };
            this.xrLabel21.ExpressionBindings.AddRange(bindingArray28);
            this.xrLabel21.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel21.LocationFloat = new PointFloat(0f, 54.00003f);
            this.xrLabel21.Multiline = true;
            this.xrLabel21.Name = "xrLabel21";
            this.xrLabel21.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel21.SizeF = new SizeF(117.7083f, 27f);
            this.xrLabel21.StylePriority.UseBorders = false;
            this.xrLabel21.StylePriority.UseFont = false;
            this.xrLabel21.StylePriority.UseTextAlignment = false;
            this.xrLabel21.TextAlignment = TextAlignment.MiddleCenter;
            this.xrLabel14.Borders = BorderSide.Top;
            this.xrLabel14.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel14.LocationFloat = new PointFloat(111.3332f, 26.99998f);
            this.xrLabel14.Multiline = true;
            this.xrLabel14.Name = "xrLabel14";
            this.xrLabel14.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel14.SizeF = new SizeF(133.6668f, 27f);
            this.xrLabel14.StylePriority.UseBorders = false;
            this.xrLabel14.StylePriority.UseFont = false;
            this.xrLabel14.Text = "۶- محل صدور شناسنامه :";
            this.xrLabel15.Borders = BorderSide.Top | BorderSide.Left;
            ExpressionBinding[] bindingArray29 = new ExpressionBinding[] { new ExpressionBinding("BeforePrint", "Text", "[محل صدور]") };
            this.xrLabel15.ExpressionBindings.AddRange(bindingArray29);
            this.xrLabel15.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel15.LocationFloat = new PointFloat(2.384186E-07f, 26.99998f);
            this.xrLabel15.Multiline = true;
            this.xrLabel15.Name = "xrLabel15";
            this.xrLabel15.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel15.SizeF = new SizeF(111.3332f, 27f);
            this.xrLabel15.StylePriority.UseBorders = false;
            this.xrLabel15.StylePriority.UseFont = false;
            this.xrLabel15.StylePriority.UseTextAlignment = false;
            this.xrLabel15.TextAlignment = TextAlignment.MiddleCenter;
            this.xrLabel12.Borders = BorderSide.Top | BorderSide.Left;
            this.xrLabel12.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel12.LocationFloat = new PointFloat(244.7917f, 26.99998f);
            this.xrLabel12.Multiline = true;
            this.xrLabel12.Name = "xrLabel12";
            this.xrLabel12.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel12.SizeF = new SizeF(153.25f, 27f);
            this.xrLabel12.StylePriority.UseBorders = false;
            this.xrLabel12.StylePriority.UseFont = false;
            this.xrLabel12.StylePriority.UseTextAlignment = false;
            this.xrLabel12.Text = "\r\n";
            this.xrLabel12.TextAlignment = TextAlignment.MiddleCenter;
            this.xrLabel13.Borders = BorderSide.Top;
            this.xrLabel13.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel13.LocationFloat = new PointFloat(398.0417f, 26.99998f);
            this.xrLabel13.Multiline = true;
            this.xrLabel13.Name = "xrLabel13";
            this.xrLabel13.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel13.SizeF = new SizeF(77.08331f, 27f);
            this.xrLabel13.StylePriority.UseBorders = false;
            this.xrLabel13.StylePriority.UseFont = false;
            this.xrLabel13.Text = "۵- تاریخ تولد :";
            this.xrLabel10.Borders = BorderSide.Top;
            this.xrLabel10.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel10.LocationFloat = new PointFloat(575.125f, 26.99998f);
            this.xrLabel10.Multiline = true;
            this.xrLabel10.Name = "xrLabel10";
            this.xrLabel10.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel10.SizeF = new SizeF(85.41666f, 27f);
            this.xrLabel10.StylePriority.UseBorders = false;
            this.xrLabel10.StylePriority.UseFont = false;
            this.xrLabel10.Text = "۴- نام پدر :";
            this.xrLabel11.Borders = BorderSide.Top | BorderSide.Left;
            ExpressionBinding[] bindingArray30 = new ExpressionBinding[] { new ExpressionBinding("BeforePrint", "Text", "[نام پدر]") };
            this.xrLabel11.ExpressionBindings.AddRange(bindingArray30);
            this.xrLabel11.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel11.LocationFloat = new PointFloat(475.125f, 26.99998f);
            this.xrLabel11.Multiline = true;
            this.xrLabel11.Name = "xrLabel11";
            this.xrLabel11.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel11.SizeF = new SizeF(99.99997f, 27f);
            this.xrLabel11.StylePriority.UseBorders = false;
            this.xrLabel11.StylePriority.UseFont = false;
            this.xrLabel11.StylePriority.UseTextAlignment = false;
            this.xrLabel11.TextAlignment = TextAlignment.MiddleCenter;
            this.xrLabel9.Borders = BorderSide.Top | BorderSide.Left;
            ExpressionBinding[] bindingArray31 = new ExpressionBinding[] { new ExpressionBinding("BeforePrint", "Text", "[شماره شناسنامه]") };
            this.xrLabel9.ExpressionBindings.AddRange(bindingArray31);
            this.xrLabel9.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel9.LocationFloat = new PointFloat(2.384186E-07f, 1.144409E-05f);
            this.xrLabel9.Multiline = true;
            this.xrLabel9.Name = "xrLabel9";
            this.xrLabel9.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel9.SizeF = new SizeF(134.125f, 27f);
            this.xrLabel9.StylePriority.UseBorders = false;
            this.xrLabel9.StylePriority.UseFont = false;
            this.xrLabel9.StylePriority.UseTextAlignment = false;
            this.xrLabel9.TextAlignment = TextAlignment.MiddleCenter;
            this.xrLabel8.Borders = BorderSide.Top;
            this.xrLabel8.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel8.LocationFloat = new PointFloat(134.125f, 0f);
            this.xrLabel8.Multiline = true;
            this.xrLabel8.Name = "xrLabel8";
            this.xrLabel8.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel8.SizeF = new SizeF(110.5834f, 27f);
            this.xrLabel8.StylePriority.UseBorders = false;
            this.xrLabel8.StylePriority.UseFont = false;
            this.xrLabel8.Text = "۳- شماره شناسنامه :";
            this.xrLabel7.Borders = BorderSide.Top | BorderSide.Left;
            ExpressionBinding[] bindingArray32 = new ExpressionBinding[] { new ExpressionBinding("BeforePrint", "Text", "[نام]") };
            this.xrLabel7.ExpressionBindings.AddRange(bindingArray32);
            this.xrLabel7.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel7.LocationFloat = new PointFloat(244.7917f, 0f);
            this.xrLabel7.Multiline = true;
            this.xrLabel7.Name = "xrLabel7";
            this.xrLabel7.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel7.SizeF = new SizeF(127.0833f, 27f);
            this.xrLabel7.StylePriority.UseBorders = false;
            this.xrLabel7.StylePriority.UseFont = false;
            this.xrLabel7.StylePriority.UseTextAlignment = false;
            this.xrLabel7.Text = "\r\n";
            this.xrLabel7.TextAlignment = TextAlignment.MiddleCenter;
            this.xrLabel6.Borders = BorderSide.Top;
            this.xrLabel6.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel6.LocationFloat = new PointFloat(371.875f, 0f);
            this.xrLabel6.Multiline = true;
            this.xrLabel6.Name = "xrLabel6";
            this.xrLabel6.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel6.SizeF = new SizeF(64.58331f, 27f);
            this.xrLabel6.StylePriority.UseBorders = false;
            this.xrLabel6.StylePriority.UseFont = false;
            this.xrLabel6.Text = "۲- نام :";
            this.xrLabel5.Borders = BorderSide.Top | BorderSide.Left;
            ExpressionBinding[] bindingArray33 = new ExpressionBinding[] { new ExpressionBinding("BeforePrint", "Text", "[نام خانوادگی]") };
            this.xrLabel5.ExpressionBindings.AddRange(bindingArray33);
            this.xrLabel5.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel5.LocationFloat = new PointFloat(436.4583f, 0f);
            this.xrLabel5.Multiline = true;
            this.xrLabel5.Name = "xrLabel5";
            this.xrLabel5.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel5.SizeF = new SizeF(138.6667f, 27f);
            this.xrLabel5.StylePriority.UseBorders = false;
            this.xrLabel5.StylePriority.UseFont = false;
            this.xrLabel5.StylePriority.UseTextAlignment = false;
            this.xrLabel5.TextAlignment = TextAlignment.MiddleCenter;
            this.xrLabel4.Borders = BorderSide.Top;
            this.xrLabel4.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel4.LocationFloat = new PointFloat(575.125f, 0f);
            this.xrLabel4.Multiline = true;
            this.xrLabel4.Name = "xrLabel4";
            this.xrLabel4.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel4.SizeF = new SizeF(85.41666f, 27f);
            this.xrLabel4.StylePriority.UseBorders = false;
            this.xrLabel4.StylePriority.UseFont = false;
            this.xrLabel4.Text = "۱- نام خانوادگی :";
            this.xrLabel3.Borders = BorderSide.Top | BorderSide.Left;
            this.xrLabel3.Font = new Font("B Nazanin", 10f, FontStyle.Bold);
            this.xrLabel3.LocationFloat = new PointFloat(660.5416f, 0f);
            this.xrLabel3.Multiline = true;
            this.xrLabel3.Name = "xrLabel3";
            this.xrLabel3.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel3.SizeF = new SizeF(82.29169f, 107f);
            this.xrLabel3.StylePriority.UseBorders = false;
            this.xrLabel3.StylePriority.UseFont = false;
            this.xrLabel3.Text = "الف)\r\n\r\nمشخصات\r\n\r\nکارگر";
            this.xrLabel2.Font = new Font("B Nazanin", 16f, FontStyle.Bold);
            this.xrLabel2.LocationFloat = new PointFloat(298.9583f, 27f);
            this.xrLabel2.Multiline = true;
            this.xrLabel2.Name = "xrLabel2";
            this.xrLabel2.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel2.SizeF = new SizeF(100f, 27f);
            this.xrLabel2.StylePriority.UseFont = false;
            this.xrLabel2.StylePriority.UseTextAlignment = false;
            this.xrLabel2.Text = "قرارداد";
            this.xrLabel2.TextAlignment = TextAlignment.MiddleCenter;
            this.xrLabel1.Font = new Font("B Nazanin", 12f, FontStyle.Bold);
            this.xrLabel1.LocationFloat = new PointFloat(298.9583f, 0f);
            this.xrLabel1.Multiline = true;
            this.xrLabel1.Name = "xrLabel1";
            this.xrLabel1.Padding = new PaddingInfo(2, 2, 0, 0, 100f);
            this.xrLabel1.SizeF = new SizeF(100f, 27f);
            this.xrLabel1.StylePriority.UseFont = false;
            this.xrLabel1.StylePriority.UseTextAlignment = false;
            this.xrLabel1.Text = "بسمه تعالی";
            this.xrLabel1.TextAlignment = TextAlignment.MiddleCenter;
            this.bindingSource1.DataMember = "MKView_ContractHamkaran";
            this.bindingSource1.DataSource = this.fishDataSet;
            this.fishDataSet.DataSetName = "FishDataSet";
            this.fishDataSet.SchemaSerializationMode = SchemaSerializationMode.IncludeSchema;
            this.mKView_ContractHamkaranTableAdapter.ClearBeforeFill = true;
            Band[] bands = new Band[] { this.TopMargin, this.BottomMargin, this.Detail };
            base.Bands.AddRange(bands);
            IComponent[] components = new IComponent[] { this.bindingSource1, this.fishDataSet };
            base.ComponentStorage.AddRange(components);
            base.DataSource = this.bindingSource1;
            this.Font = new Font("Arial", 9.75f);
            base.Margins = new Margins(0x35, 0x2f, 0, 0x4f);
            base.Version = "19.1";
            ((ISupportInitialize)this.bindingSource1).EndInit();
            this.fishDataSet.EndInit();
            this.EndInit();
        }

        private void xrLabel89_BeforePrint(object sender, PrintEventArgs e)
        {
            this.xrLabel12.Text = new MD.PersianDateTime.PersianDateTime(((FishDataSet.MKView_ContractHamkaranRow)this.fishDataSet.MKView_ContractHamkaran.Rows[0]).تاریخ_تولد).ToShortDateString();
            this.xrLabel52.Text = this.startDate;
            this.xrLabel54.Text = this.endDate;
        }
    }
}