//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZarkiaIntegratedSystem_Tax
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Insurence_PersonalInfo
    {
        public string DSW_SDATE { get; set; }// تاریخ شروع به کار
        public string DSW_EDATE { get; set; }// تاریخ ترک کار
        public int DSW_MASH { get; set; }// جمع دستمزد و مزایای ماهانه مشمول  ) ناخالص دریافتی)
        public string piMeliCode { get; set; }// کد ملی
        public string piFName { get; set; }// نام
        public string piLName { get; set; } // نام خانوادگی
        public int piOneDaySalary { get; set; }// حقوق یک روز; }
        public int piInsurenceType { get; set; } // نوع بیمه
        public int startWorkDate { get; set; } // تاریخ شروع به کار
        public string JobName { get; set; }//نام شغل
        public string ServiceLocation { get; set; } // شهر محل خدمت
    }
}
